### PR TITLE
Remove radio-based hardware capabilities

### LINKED ISSUE #50: Make sure radio cannot be enabled by contestants
We should make sure that contestants are not able to start up Bluetooth or WiFi. We should also consider disabling the camera.

### PR DESCRIPTION
**Pull request by horcsinbalint**
Should fix #50.

### CODE REVIEW

**Comment by radl97** [comment]
If someone at a later year wants to update the set of blacklisted modules, where should one start?

Can you add a comment on how you determined the set of modules? (Always think about how hard it is pretty hard to update every little detail when handed a big repo with many miniscule and seemingly unimportant details. E.g. document why there is A and not B, why only these modules are blacklisted, etc.)

**Comment by horcsinbalint** [comment]
Okay, it's 100% true.
I will add documentation for it.

**Review by radl97 — APPROVED** [review]
Great work! Thanks for documenting the details!

**Comment by radl97** [comment]
I think I'll squash the changes, and apply these into a different branch. (the VM does not need it)

**Comment by radl97** [comment]
Done. See #63

**Pull request closed without merging**
